on: [push]

jobs:
  rebase_check:
    runs-on: ubuntu-latest
    name: 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check if rebase is needed
      id: rebase
      uses: mfocko/rebase-check-action@try-alpine

